name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: echo "this is test"
      - name: checkout
        uses: actions/checkout@v2
      - name: ls
        run: |
          ls -al
          cd .github/workflows/
          ls -al
